import Providers from '@/libs/redux/providers';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    lang: string;
  };
};

export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <Providers>
      <html lang={params.lang} className="dark">
        <body className={`${inter.className} dark:bg-black`}>{children}</body>
      </html>
    </Providers>
  );
}
