import Providers from '@/libs/redux/providers';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    lang: string;
  };
};

export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <Providers>
      <html lang={params.lang} className="dark">
        <body className={`${inter.className} dark:bg-black`}>
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar
            newestOnTop={false}
            pauseOnFocusLoss={false}
            rtl={false}
            theme="dark"
            pauseOnHover
          />
          {children}
        </body>
      </html>
    </Providers>
  );
}
